# Etiquetas globales para identificar que es parte de tu stack
extraLabels:
    part-of: microservices-platform

server:

  # Habilitamos el almacenamiento persistente para no perder
  # los secretos si se reinicia el cluster
  dataStorage:
    enabled: true
    size: 5Gi

# Interfaz Gráfica (UI)
ui:
  enabled: true
  serviceType: ClusterIP
  serviceNodePort: null
  externalPort: 8200