apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: elasticsearch
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: elasticsearch
    namespace: monitoring
    valuesFile: elasticsearch-values.yaml

  - name: kibana
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: kibana
    namespace: monitoring
    valuesFile: kibana-values.yaml

  - name: filebeat
    repo: https://helm.elastic.co
    version: 8.5.1
    releaseName: filebeat
    namespace: monitoring
    valuesFile: filebeat-values.yaml