apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

resources:
  - cluster-operator.yml       # Operador RabbitMQ (ClusterRole, Deployment, etc.)
  - rabbitmq-cluster.yaml      # Definición del clúster RabbitMQ (Custom Resource)