apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: event-management
  labels:
    part-of: microservices-platform
spec:
  replicas: 1   # Para desarrollo
  image: rabbitmq:4.1.0-management
  resources:
    requests:
      cpu: 100m      # Reducir de 500m a 100m
      memory: 512Mi  # Reducir de 1Gi a 512Mi
    limits:
      cpu: 500m      # Reducir de 2000m a 500m
      memory: 1Gi
  persistence:
    storageClassName: standard
    storage: 10Gi
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = changeme
      default_user_tags.administrator = true
      prometheus.return_per_object_metrics = true
  service:
    type: ClusterIP