# gitlab-sonarqube-values.yaml – Configuración minimalista para repositorio GitLab
global:
  common:
    labels:
      part-of: microservices-platform

  edition: ce

  hosts:
    domain: gitlab.desarrollo
    https: false

  ingress:
    configureCertmanager: false
    tls:
      enabled: false

  redis:
    host: redis.event-management.svc.cluster.local
    port: 6379
    auth:
      enabled: false

  # ============================================================
  # CONFIGURACIÓN DE BASE DE DATOS EXTERNA (la base de datos debe estar previamente creada)
  # ============================================================
  psql:
    host: postgresql.devops-tools.svc.cluster.local
    port: 5432
    username: gitlab
    database: gitlabhq_production
    password:
      secret: gitlab-postgres-password
      key: password
#    password:
#      plain: "gitlab789"
    # Opcional: ajustar si usas SSL (en desarrollo no es necesario)
    sslmode: disable

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus

  appConfig:
    lfs:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    ci:
      incremental_logging: false

  kas:
    enabled: false

nginx-ingress:
  enabled: false

registry:
  enabled: false

prometheus:
  install: false

redis:
  install: false

gitlab-runner:
  install: false

postgresql:
  install: false

webservice:
  logLevel: debug
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

sidekiq:
  logLevel: debug
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi

gitlab:
  gitlab-exporter:
    enabled: false
  registry:
    enabled: false
  pages:
    enabled: false
  gitlab-prometheus:
    enabled: false
  nginx-ingress:
    enabled: false
  toolbox:
    enabled: false
  mailroom:
    enabled: false
  spamcheck:
    enabled: false
  gitlab-pages:
    enabled: false
  praefect:
    enabled: false
  geo-logcursor:
    enabled: false