apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: repositories

helmCharts:
  - name: gitlab
    repo: https://charts.gitlab.io
    version: 9.11.2
    releaseName: gitlab
    namespace: repositories
    valuesFile: gitlab-values.yaml