apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

helmCharts:
  - name: aqua-trivy-operator
    repo: https://aquasecurity.github.io/helm-charts
    version: 0.32.1
    releaseName: aqua-trivy-operator-0.32.1
    namespace: security
    valuesFile: trivy-values.yaml