commonLabels:
  part-of: microservices-platform

operator:
  # Escaneamos casi todo, excepto el core intocable
  excludeNamespaces: "kube-system,kube-public"
  # Habilitamos auditoría de configuración y RBAC
  configAuditScannerEnabled: true
  rbacScannerEnabled: true
  # Generar reportes de cumplimiento (CIS/NSA)
  complianceEnabled: true

  podLabels:
    part-of: microservices-platform

trivy:
  # Límites realistas para tus 28GB de clúster
  resources:
    requests:
      cpu: "100m"    # Agregar requests explícitos
      memory: "512Mi"
    limits:
      cpu: "500m"    # Reducir de 1000m a 500m
      memory: "1Gi"
  # Ignorar vulnerabilidades sin parche disponible (Fixed)
  # para evitar ruido innecesario
  ignoreUnfixed: true
  # Nivel mínimo de severidad para reportar
  severity: "HIGH,CRITICAL"


# SERVICEMONITOR PARA PROMETHEUS
serviceMonitor:
  enabled: true
  labels:
    release: prometheus  # Debe coincidir con tu Prometheus Operator
  interval: 60s  # Scrape cada 60 segundos