package edu.market.notification.domain.enums;

public enum EventType {

    NOTIFICATION_CANCELED,
    NOTIFICATION_CREATED,
    NOTIFICATION_FAILED,
    NOTIFICATION_SCHEDULED,
    NOTIFICATION_DISABLED,
    NOTIFICATION_SENT,
    SUSBCRIPTION_CHANGED,
    USER_PREFERENCE_CHANGED,
    TEMPLATE_CHANGED,
    TEMPLATE_CREATED;
}