apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-tools

helmCharts:
  - name: artifactory-oss
    repo: https://charts.jfrog.io
    version: 107.146.8
    releaseName: artifactory-oss
    namespace: devops-tools
    valuesFile: artifactory-oss-values.yaml