apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-webservice-metrics
  namespace: repositories
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gitlab-webservice-default # GitLab usa una nomenclatura de labels particular
  namespaceSelector:
    matchNames:
      - repositories
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
