apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
  labels:
    app: nexus
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/nexus"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-data-pv
  labels:
    app: jenkins
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/jenkins"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  labels:
    app: elasticsearch
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/minikube/nfs-mnt/elasticsearch"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-pv
  labels:
    app: rabbitmq
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/rabbitmq"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  labels:
    app: redis
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/redis"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data-pv
  labels:
    app: prometheus
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/prometheus-stack"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-data-pv
  labels:
    app: jaeger
    type: external-persistent
    part-of: microservices-platform
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/microservices-architecture/mnt/jeager"