apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: external-secrets
  namespace: secrets-manager
spec:
  authentication:
    path: kubernetes
    role: vault-config-operator
    serviceAccount:
      name: default
  path: kubernetes
  policies:
    - external-secrets
  targetServiceAccounts:
    - external-secrets-vault
  targetNamespaces:
    targetNamespaces:
      - security
