global:
  commonLabels:
    part-of: microservices-platform

crds:
  enabled: true

fullnameOverride: cert-manager-v1-18-2

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi