# Etiquetas globales para tu arquitectura
commonLabels:
  part-of: microservices-platform

# Configuración de la API y el Dashboard
api:
  dashboard: true
  insecure: true # Para acceso rápido en desarrollo

ingressRoute:
  dashboard:
    enabled: true
    matchRule: "Host(`traefik.desarrollo`)" # Tu dominio de desarrollo
    entryPoints: ["web"]

# Observabilidad
logs:
  access:
    enabled: true
    level: DEBUG
    format: json

# Metrics
metrics:
  # Enable providing OTel metrics
  otlp:
    enabled: true
    http:
      enabled: true
  prometheus:
    addEntryPointsLabels: true

# Tracing
tracing:
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: "http://jaeger.monitoring.svc.cluster.local:4318/v1/traces"

# Gateway API (Habilitado según tu comando original)
providers:
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All

# Configuración del servicio para Minikube
service:
  type: LoadBalancer