# Etiquetas globales para todos los recursos creados por el Chart
commonLabels:
  part-of: microservices-platform

# Recursos para el binario principal (Jaeger V2 usa un solo despliegue por defecto)
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 512Mi

userconfig:

  service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [jaeger_storage_exporter]
    telemetry:
      resource:
        service.name: jaeger
      metrics:
        level: detailed
        readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  extensions:
    healthcheckv2:
      use_v2: true
      http:
        endpoint: 0.0.0.0:13133
    jaeger_query:
      storage:
        traces: primary_store_elasticsearch
        traces_archive: archive_store_elasticsearch
    jaeger_storage:
      backends:
        primary_store_elasticsearch:
          elasticsearch:
            server_urls: ["https://elasticsearch-master.monitoring.svc.cluster.local:9200"]
            auth:
              basic:
                username: elastic
                password: ZeLWSazaFjOCXPuF
            tls:
              insecure_skip_verify: true
        archive_store_elasticsearch:
          elasticsearch:
            server_urls: ["https://elasticsearch-master.monitoring.svc.cluster.local:9200"]
            auth:
              basic:
                username: elastic
                password: ZeLWSazaFjOCXPuF
            tls:
              insecure_skip_verify: true

  exporters:
    jaeger_storage_exporter:
      trace_storage: primary_store_elasticsearch

esIndexCleaner:
  enabled: true

storage:
  elasticsearch:
    tls:
      enabled: true
      skip_verify: true
    url: "https://elasticsearch-master.monitoring.svc.cluster.local:9200"
    user: elastic
    password: ZeLWSazaFjOCXPuF

# ------------------------------------------------------------------------------
# Objetos adicionales (Aquí es donde inyectamos el puente a Prometheus)
# ------------------------------------------------------------------------------
extraObjects:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: jaeger-metrics-monitor
      labels:
        # Crucial: ajusta 'prometheus' al nombre de tu release del stack
        release: prometheus
        part-of: microservices-platform
    spec:
      namespaceSelector:
        matchNames:
          - monitoring
      selector:
        matchLabels:
          app.kubernetes.io/instance: jaeger
          app.kubernetes.io/name: jaeger
      endpoints:
        - port: internal-metrics
          interval: 15s
          path: /metrics