apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    version: 4.7.0
    releaseName: jaeger
    namespace: monitoring
    valuesFile: jaeger-values.yaml