spring:

  config:
    import: optional:configserver:http://localhost:8890

  application:
    name: user-service
  
  profiles:
    active: dev

  cloud:
    config:
      enabled: false
      uri: http://config-server:8890
  
  datasource:
    url: jdbc:h2:mem:notificationdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000 # Cambia por la URL real de tu auth-server
server:
  port: 0 # Puerto aleatorio para evitar conflictos en desarrollo



eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10


springdoc:  
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    prefer-ip-address: false


# Configuración de logging
logging:
  level:
    root: INFO   # Nivel general para toda la aplicación
    edu.market.userservice: DEBUG   # Nivel DEBUG para tus paquetes específicos
    org.springframework.security: INFO   # Configuración específica para Spring Security
    org.springframework.web: INFO   # Configuración para componentes web de Spring
    org.hibernate: INFO   # Configuración general para Hibernate
    org.hibernate.SQL: ERROR   # Muestra todas las consultas SQL ejecutadas
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR   # Muestra los valores de los parámetros en las consultas

# Propiedades personalizadas (pueden ser sobreescritas por config-server)
custom:
  example-property: valor-por-defecto
  auth:
    token:
      access-token-duration-minutes: 30
      refresh-token-duration-days: 7
  
