apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    part-of: microservices-platform
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # <--- Cambio a HTTP
      path: "secret"
      version: "v2"
      # Eliminado el bloque tls:
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "security" # El token vive en el namespace de ESO