apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  labels:
    part-of: microservices-platform
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      tls:
        caCert:
          secretRef:
            name: vault-tls
            key: ca.crt
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: vault