apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-metrics
  namespace: security
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  namespaceSelector:
    matchNames:
      - security
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s