apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: <NAMESPACE_DEL_COMPONENTE>

helmCharts:
  - name: <NOMBRE_DEL_CHART>
    repo: <URL_DEL_REPO_HELM>
    version: <VERSION>
    releaseName: <RELEASE_NAME>
    namespace: <NAMESPACE_DEL_COMPONENTE>
    valuesFile: values.yaml