# Etiquetas globales para mantener la coherencia con tu proyecto de microservicios
labels:
  part-of: microservices-platform

# 1. Configuración de Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    # Retención de datos: cuánto tiempo se guardan las métricas antes de borrarse
    retention: 10d

    # Persistencia: Vital para no perder tus gráficas y datos al reiniciar pods
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# 2. Configuración de Grafana
grafana:
  enabled: true
  adminPassword: "admin" # Cambia esto por una contraseña segura

  # Persistencia para Grafana (evita perder dashboards creados manualmente)
  persistence:
    enabled: true
    type: pvc
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

    # 2. SOLUCIÓN AL PERMISSION DENIED:
    # Estas propiedades NO están en el bloque 'adminApi',
    # deben colgar directamente de 'grafana:'

  initChownData:
    enabled: false # Desactiva el contenedor que da error

  podSecurityContext:
    fsGroup: 472 # Asigna el permiso al volumen desde K8s

  containerSecurityContext:
    runAsUser: 472
    runAsGroup: 472