apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: _prometheus/metrics
      interval: 30s
