apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: filebeat-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: filebeat
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /stats
      interval: 30s
