apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kibana-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /api/prometheus/metrics
      interval: 30s
