labels:
  part-of: microservices-platform

# Definición de recursos que consumira el componente
resources:
  requests:
    cpu: "50m"       # Reducir de 500m a 50m
    memory: "512Mi"  # Reducir de 1Gi a 512Mi
  limits:
    cpu: "300m"      # Agregar límite explícito
    memory: "1Gi"    # Mantener


kibanaConfig:
  kibana.yml: |
    server.ssl.enabled: false
    elasticsearch.hosts: ["https://elasticsearch-master:9200"]    
    elasticsearch.ssl.verificationMode: none   # Equivalente a insecure_skip_verify
    xpack.security.secureCookies: false


# Deshabilita el job conflictivo
createKibanaTokenJob:
  enabled: false

readinessProbe: {}

elasticsearchHosts: "https://elasticsearch-master:9200"
protocol: https