apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-services

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.6.2
    releaseName: postgresql
    namespace: data-services
    valuesFile: postgresql-values.yaml

  - name: pgadmin4
    repo: https://helm.runix.net
    version: 1.62.0
    releaseName: pgadmin4
    namespace: data-services
    valuesFile: pgadmin-values.yaml