commonLabels:
  part-of: microservices-platform

image:
  repository: dpage/pgadmin4
  tag: "9.13"
  pullPolicy: IfNotPresent

env:
  email: "admin@desarrollo.edu"
  enhanced_cookie_protection: "False"

serverDefinitions:
  enabled: true
  servers:
    dev-postgres:
      Name: "PostgreSQL - data-services"
      Group: "Servers"
      Port: 5432
      Username: "postgres"
      Host: "postgresql.data-services.svc.cluster.local"
      SSLMode: "prefer"
      MaintenanceDB: "postgres"

persistentVolume:
  enabled: true
  size: 1Gi
  storageClass: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

# Aumentar recursos
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Desactivar startup probe (no es crítica) y ajustar las sondas
startupProbe: {}

readinessProbe:
  httpGet:
    path: /misc/ping
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  httpGet:
    path: /misc/ping
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3