# Etiquetas globales
labels:
  part-of: microservices-platform

# Configuración del recurso Redis (standalone)
redisStandalone:
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 500Mi
  persistence:
    enabled: true
    storageClassName: standard
    storageSize: 3Gi
  # Desactivar autenticación (opcional)
  redisSecret:
    secretName: ""   # si no se usa contraseña


# ServiceMonitor para Prometheus
serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  interval: 30s