CREATE TABLE PROPERTIES (
    APPLICATION VARCHAR(50),
    PROFILE VARCHAR(50),
    LABEL VARCHAR(50),
    PROP_KEY VARCHAR(100),
    PROP_VALUE VARCHAR(2000)
);

CREATE INDEX idx_app_profile_label ON PROPERTIES (APPLICATION, PROFILE, LABEL);
