apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
  namespace: data-services
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis # Etiqueta estándar de Bitnami
  namespaceSelector:
    matchNames:
      - data-services
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s